/// Maps common base-asset tickers to their full names.
/// Falls back to the ticker itself for unknown symbols.
String cryptoName(String symbol) {
  final baseAsset = symbol.replaceAll('USDT', '');
  return _names[baseAsset] ?? baseAsset;
}

const _names = <String, String>{
  'BTC': 'Bitcoin',
  'ETH': 'Ethereum',
  'BNB': 'BNB',
  'SOL': 'Solana',
  'XRP': 'XRP',
  'ADA': 'Cardano',
  'DOGE': 'Dogecoin',
  'AVAX': 'Avalanche',
  'DOT': 'Polkadot',
  'TRX': 'TRON',
  'LINK': 'Chainlink',
  'MATIC': 'Polygon',
  'POL': 'Polygon',
  'SHIB': 'Shiba Inu',
  'LTC': 'Litecoin',
  'BCH': 'Bitcoin Cash',
  'ATOM': 'Cosmos',
  'UNI': 'Uniswap',
  'XLM': 'Stellar',
  'FIL': 'Filecoin',
  'NEAR': 'NEAR Protocol',
  'APT': 'Aptos',
  'ARB': 'Arbitrum',
  'OP': 'Optimism',
  'SUI': 'Sui',
  'ICP': 'Internet Computer',
  'HBAR': 'Hedera',
  'VET': 'VeChain',
  'ALGO': 'Algorand',
  'FTM': 'Fantom',
  'SAND': 'The Sandbox',
  'MANA': 'Decentraland',
  'AXS': 'Axie Infinity',
  'THETA': 'Theta Network',
  'ETC': 'Ethereum Classic',
  'AAVE': 'Aave',
  'GRT': 'The Graph',
  'MKR': 'Maker',
  'RUNE': 'THORChain',
  'INJ': 'Injective',
  'IMX': 'Immutable',
  'SEI': 'Sei',
  'TIA': 'Celestia',
  'FET': 'Fetch.ai',
  'RNDR': 'Render',
  'WIF': 'dogwifhat',
  'PEPE': 'Pepe',
  'BONK': 'Bonk',
  'FLOKI': 'Floki',
  'CRV': 'Curve DAO',
  'LDO': 'Lido DAO',
  'SNX': 'Synthetix',
  'COMP': 'Compound',
  'ENS': 'Ethereum Name Service',
  'EGLD': 'MultiversX',
  'QNT': 'Quant',
  'XMR': 'Monero',
  'EOS': 'EOS',
  'XTZ': 'Tezos',
  'FLOW': 'Flow',
  'NEO': 'Neo',
  'CFX': 'Conflux',
  'KAVA': 'Kava',
  'ZIL': 'Zilliqa',
  'ROSE': 'Oasis Network',
  'ONE': 'Harmony',
  'GALA': 'Gala',
  'ENJ': 'Enjin Coin',
  'CHZ': 'Chiliz',
  'BAT': 'Basic Attention Token',
  'ZEC': 'Zcash',
  'DASH': 'Dash',
  'IOTA': 'IOTA',
  'KSM': 'Kusama',
  'CAKE': 'PancakeSwap',
  'CRO': 'Cronos',
  'LUNC': 'Terra Classic',
  'LUNA': 'Terra',
  'GMT': 'STEPN',
  'APE': 'ApeCoin',
  'MASK': 'Mask Network',
  '1INCH': '1inch',
  'SUSHI': 'SushiSwap',
  'YFI': 'yearn.finance',
  'DYDX': 'dYdX',
  'WLD': 'Worldcoin',
  'BLUR': 'Blur',
  'JTO': 'Jito',
  'JUP': 'Jupiter',
  'PYTH': 'Pyth Network',
  'STX': 'Stacks',
  'TAO': 'Bittensor',
  'ORDI': 'ORDI',
  'PENDLE': 'Pendle',
  'W': 'Wormhole',
  'STRK': 'Starknet',
  'MEME': 'Memecoin',
  'SAGA': 'Saga',
  'DYM': 'Dymension',
  'PIXEL': 'Pixels',
  'PORTAL': 'Portal',
  'ALT': 'AltLayer',
  'AI': 'Sleepless AI',
  'JASMY': 'JasmyCoin',
  'WAVES': 'Waves',
  'ZRX': '0x',
  'STORJ': 'Storj',
  'SKL': 'SKALE',
  'CELO': 'Celo',
  'ANKR': 'Ankr',
  'RSR': 'Reserve Rights',
  'RLC': 'iExec RLC',
};
